
-----------------------------------------------------------
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (1, 'STATE');
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (2, 'CITY');
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (3, 'COMPANY');
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (4, 'BUILDING');
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (5, 'BLOCK');
INSERT INTO DICTIONARY (ID, TABLE_NAME) VALUES (6, 'DEPARTMENT');

-----------------------------------------------------------
INSERT INTO STATE (ID, NAME, SHORT_NAME) VALUES (1, 'IOWA', 'IA');

-----------------------------------------------------------
INSERT INTO CITY (ID, NAME, STATE_ID) VALUES (1, 'FAIRFIELD', 1);
INSERT INTO CITY (ID, NAME, STATE_ID) VALUES (2, 'DES MOINES', 1);

-----------------------------------------------------------
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (1, '2000 N COURT', 'TRLR 7G', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (2, '2000 N COURT', 'TRLR 7G', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (3, '3000 N COURT', 'TRLR 8G', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (4, '3000 N COURT', 'TRLR 9G', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (5, '3000 N COURT', 'TRLR 8H', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (6, '3000 N COURT', 'TRLR 3C', '52556', 1, 1);
INSERT INTO ADDRESS (ID, STREET, UNIT, ZIP_CODE, CITY_ID, STATE_ID) VALUES (7, '3000 N COURT', 'TRLR 5D', '52556', 1, 1);

-----------------------------------------------------------
INSERT INTO COMPANY (ID, MAIN_COMPANY, NAME, ADDRESS_ID) VALUES (1, 1, 'BAO NGUYEN CORP.', 1);

-----------------------------------------------------------
INSERT INTO BUILDING (ID, FAX, NAME, PHONE, ADDRESS_ID, COMPANY_ID) VALUES (1, '(641) 451-4303', 'BUILDING 1', '(641) 451-4303', 2, 1);

-----------------------------------------------------------
INSERT INTO BLOCK (ID, NAME, NO_OF_APT, NO_OF_FLOOR, BUILDING_ID) VALUES (1, 'BLOCK 1', 20, 5, 1);

-----------------------------------------------------------
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (1, 'APT 1', 1, 1, 60, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (2, 'APT 2', 1, 1, 60, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (3, 'APT 3', 1, 1, 70, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (4, 'APT 4', 1, 1, 70, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (5, 'APT 5', 2, 1, 65, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (6, 'APT 6', 2, 1, 65, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (7, 'APT 7', 2, 1, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (8, 'APT 8', 2, 1, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (9, 'APT 9', 2, 2, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (10, 'APT 10', 2, 2, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (11, 'APT 11', 2, 2, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (12, 'APT 12', 2, 2, 75, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (13, 'APT 13', 3, 2, 90, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (14, 'APT 14', 3, 2, 90, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (15, 'APT 15', 3, 2, 110, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (16, 'APT 16', 3, 2, 110, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (17, 'APT 17', 3, 2, 90, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (18, 'APT 18', 1, 1, 60, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (19, 'APT 19', 1, 1, 70, 1);
INSERT INTO APARTMENT (ID, APT_NO, BATH_ROOM, BED_ROOM, SQUARE, BLOCK_ID) VALUES (20, 'APT 20', 1, 1, 70, 1);

-----------------------------------------------------------
INSERT INTO PERSON (ID, DOB, SSN, EMAIL, FIRST_NAME, GENDER, LAST_NAME, PHONE) VALUES (1, '1991-09-10', '222-222-2222', 'THAO.DAO282@GMAIL.COM', 'THI VAN THAO', 2, 'DAO', '(641) 451-4303');
INSERT INTO PERSON (ID, DOB, SSN, EMAIL, FIRST_NAME, GENDER, LAST_NAME, PHONE) VALUES (2, '1991-12-14', '222-222-3333', 'QUANGTRINH@GMAIL.COM', 'QUANG TRINH', 1, 'NGUYEN', '(641) 451-4303');
INSERT INTO PERSON (ID, DOB, SSN, EMAIL, FIRST_NAME, GENDER, LAST_NAME, PHONE) VALUES (3, '1991-02-28', '222-222-4444', 'QUANGDANG@GMAIL.COM', 'QUANG DANG', 1, 'NGUYEN', '(641) 451-4303');
INSERT INTO PERSON (ID, DOB, SSN, EMAIL, FIRST_NAME, GENDER, LAST_NAME, PHONE) VALUES (4, '1991-06-05', '222-222-5555', 'QUANGTHIEN@GMAIL.COM', 'QUANG THIEN', 1, 'NGUYEN', '(641) 451-4303');
INSERT INTO PERSON (ID, DOB, SSN, EMAIL, FIRST_NAME, GENDER, LAST_NAME, PHONE) VALUES (5, '1991-09-22', '222-222-6666', 'LENGUYEN@GMAIL.COM', 'THI LE NGUYEN', 2, 'DAO', '(641) 451-4303');

-----------------------------------------------------------
INSERT INTO DEPARTMENT (ID, FAX, NAME, PHONE, COMPANY_ID, MANAGER) VALUES (1, '(641) 451-4304', 'HR DEPT', '(641) 451-4303', 1, NULL);

-----------------------------------------------------------
INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID, END_DATE, START_DATE, ADDRESS_ID, DEPARTMENT_ID) VALUES (1, 'EMP_01', NULL, '2018-01-01', 3, 1);
INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID, END_DATE, START_DATE, ADDRESS_ID, DEPARTMENT_ID) VALUES (2, 'EMP_02', NULL, '2019-01-01', 4, 1);

-----------------------------------------------------------
INSERT INTO CUSTOMER (ID, APARTMENT_ID, BLOCK_ID, BUILDING_ID) VALUES (3, 5, 1, 1);
INSERT INTO CUSTOMER (ID, APARTMENT_ID, BLOCK_ID, BUILDING_ID) VALUES (4, 5, 1, 1);
INSERT INTO CUSTOMER (ID, APARTMENT_ID, BLOCK_ID, BUILDING_ID) VALUES (5, 1, 1, 1);

-----------------------------------------------------------
UPDATE DEPARTMENT SET MANAGER = 1 WHERE ID = 1;

-----------------------------------------------------------
insert into user (id, active, password, username, person_id) values (1, 1, 'admin', 'admin', 1);
insert into user (id, active, password, username, person_id) values (2, 1, 'manager', 'manager', 1);
insert into user (id, active, password, username, person_id) values (3, 1, 'staff', 'staff', 2);
insert into user (id, active, password, username, person_id) values (4, 1, 'customer', 'customer', 3);

-----------------------------------------------------------
insert into role (id, role_name) values (1, 'ADMIN');
insert into role (id, role_name) values (2, 'MANAGER');
insert into role (id, role_name) values (3, 'STAFF');
insert into role (id, role_name) values (4, 'CUSTOMER');

-----------------------------------------------------------
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);